### ISSUE TITLE
Unify testing code style

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1091]
Some test suites are a bit all over the place, we should make them more consistent. Current items:

- [x] use `const` and `let` in favor of `var`
- [x] `await` instead of `.then`
- [x] `chai.should` instead of `assert`
- [x] `this` to store global variables (#1200)
- [x] remove `chai-as-promised`
- [x] use `(await promise).should.bla` instead of assigning and testing (#1201)
- [x] add names (e.g. `owner`) to accounts
- [x] remove arrow functions where they [shouldn't be used](https://mochajs.org/#arrow-functions) (#1202)
- [x] use `expectEvent` to test logs-related stuff (#1232)

**Comment by nventuro** [comment]
We should also remove `chai-as-promised`, since [it doesn't work properly when combined with `chai-bignumber'](https://github.com/domenic/chai-as-promised/issues/244), is not being maintained, and can be replaced by `(await promise)` anyway.

**Comment by frangio** [comment]
I added an item about arrow functions. There is [a section](https://mochajs.org/#arrow-functions) in the Mocha website about them. I could find incorrect use of arrow functions in the tests for: `Superuser`, `ECRecovery`, `RBAC`, and `SignatureBouncer`.

@nventuro Not sure if we should also open an issue for this. Are you tracking each item separately also?

**Comment by nventuro** [comment]
Tbh I'm not doing great work at handling this, I should've opened separate issues (and maybe a meta-issue?). Thanks for the bit about arrouw functions!

**Comment by nventuro** [comment]
This should be easier to track now.

**Comment by nventuro** [comment]
This is now ready, thanks @jacobherrington, @justuswilhelm and @Aniket-Engg! :tada:
