### ISSUE TITLE
Publish testing suite and behavior fixtures

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1204]
This will probably be the biggest 2.1 feature: we want to publish our testing suite on the npm package, along with helpers, behaviors, etc., so users can more easily and correctly test their code. A lot of work is required before this can be achieved though:

 - [ ] Add a testing guide (#1077)
 - [ ] Improve test descriptions (#1157)
 - [x] Test the helpers (https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1078)
 - [x] Improve the EVM exception helpers (https://github.com/OpenZeppelin/openzeppelin-solidity/issues/942)
 - [x] Improve the logging helpers (#1026)
 - [ ] Set standards for our behaviors and document them (https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1085)

**Comment by nventuro** [comment]
https://github.com/OpenZeppelin/openzeppelin-test-helpers is now a thing!
